"""add slug to blog model

Revision ID: e58636ecc1c1
Revises: cedf4fedd4fe
Create Date: 2025-07-24 06:32:19.155727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e58636ecc1c1'
down_revision: Union[str, Sequence[str], None] = 'cedf4fedd4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.create_unique_constraint(None, 'blog', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='unique')
    op.drop_column('blog', 'slug')
    # ### end Alembic commands ###
